src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Posting__c.object
<CustomObject>
    <description>Represents the junction object between a position and an employment website</description>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Employment Websites</relationshipLabel>
        <relationshipName>Job_Postings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DemoAcc.cls
public class DemoAcc {
    
    public static void getAccount(){
        List<Account> accountList = [SELECT Id, Name, Type, RecordTypeId, Active__c FROM Account limit 100];
        system.debug('@@accountList'+accountList);
        
        List<Job_Posting__c> jibList = [SELECT Id, LastModifiedById, Name, CreatedById, Position__c FROM Job_Posting__c];
                system.debug('@@jibList'+jibList);

            
    }

}